project:
  type: book
  output-dir: docs
  preview:
    browser: false

book:
  title: "From Beta to Meaning: A Guide to Interpreting Regression Analysis"
  author: "André Walter"
  chapters:
    - index.qmd
    - chapters/Categorical_Compositional.qmd
    - chapters/Comparing_Estimates.qmd
    - chapters/Interaction_Polynomials.qmd
    - chapters/Spatial_Weights_Matrices.qmd


bibliography: references.bib

format:
  html:
    toc: true
    number-sections: true
    html-math-method: mathjax
    css: styles.css
