---
title: "Introduction"
---

## Why this book

Why another book on statistics? There are already many excellent introductions, both technical and non-technical, and many are freely available online. Some focus on the mathematical foundations of statistics, while others provide practical guidance on applying statistical methods across contexts or implementing them in software such as R, Python, or Stata. Still others are tailored to specific disciplines and industries such as health and biostatistics, engineering, economics, and business. So why write another one?

There are two reasons why I decided to write this book. First, coding and implementing statistics into software is a skill that is likely to become less important with the arrival of AI-coding assistants. Most agents such as Claude Code or Codex can write better code in R, SQL, Python or other languages than most humans, and they can do it much faster. While some coding skills will still be necessary to understand how to use these tools as well as to debug and adjust code for specific use cases, the need to write code from scratch will likely diminish over time. What will become more important, however, is the ability to clearly communicate what a user wants an agent to do and how to understand and interpret the results that an agent produces.

This brings me to the second reason for writing this book. The book is also going to be the book that I hoped I had when I was learning statistics and doing research as a PhD student. While there were many great books on statistics already available, I found that there were a lot of open questions when doing quantitative research that were not covered in these books.  

## Roadmap

Outline the main themes and how the chapters connect.
